# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5977dfd6d4ce9221a402b8b91549dbefc46097c8ebc9de4f70835c86e387901000d81a07dd4cc0e9975c89564fa8e90ac703c6d22bcfe208ee958eccc1bb1c72

test:
  secret_key_base: 11e7e6e4c8d303d0c5bf492d8a8c04b4a1d02f90589199f3a978f85e30be4b3f323a380cf2b7de3dd8270d3d5c5c3f2f3a4761233b8b7c501c327a28997a1fa3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
